version: '3.1'

services:
  postgres:
    container_name: postgres_websockets
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: websockets
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres
  server:
    container_name: server_websockets
    image: node:lts-alpine
    volumes:
      - ./server:/usr/local/server
    working_dir: /usr/local/server
    ports:
      - '8000:8000'
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run watch
  client:
    container_name: client_websockets
    image: node:lts
    volumes:
      - ./client:/var/www/html/app
    working_dir: /var/www/html/app
    ports:
      - '3000:3000'
    command: 
      - /bin/sh
      - -c
      - |
        npm install
        npm run dev
    tty: true

